// Client-safe blog types and constants. No fs / no server-only imports.

export const BLOG_CATEGORIES = [
  'Bridal Tips',
  'South Asian Weddings',
  'Makeup Trends',
  'GTA Weddings',
] as const

export type BlogCategory = (typeof BLOG_CATEGORIES)[number]

export interface BlogFrontmatter {
  title:         string
  date:          string
  excerpt:       string
  category:      BlogCategory
  readTime:      string
  coverImage:    string
  featured?:     boolean
  // Set `published: false` in frontmatter to keep a post out of the
  // listing/static-params but still in the repo for editing.
  published?:    boolean
  // Tagged true by the autonomous blog engine for traceability.
  autoGenerated?: boolean
  // SEO target keyword the post was written against (engine only — humans can omit).
  targetKeyword?: string
}

export interface BlogPost extends BlogFrontmatter {
  slug:    string
  content: string
}
