import 'server-only'
import fs from 'node:fs'
import path from 'node:path'
import matter from 'gray-matter'
import type { BlogCategory, BlogPost } from './blogTypes'

export { BLOG_CATEGORIES, type BlogCategory, type BlogFrontmatter, type BlogPost } from './blogTypes'

const POSTS_DIR = path.join(process.cwd(), 'content', 'blog')

function readPostFile(filename: string): BlogPost | null {
  const fullPath = path.join(POSTS_DIR, filename)
  if (!fs.existsSync(fullPath)) return null

  const raw  = fs.readFileSync(fullPath, 'utf8')
  const { data, content } = matter(raw)
  // Prefer slug from frontmatter (lets you rename files without breaking URLs);
  // fall back to the filename otherwise.
  const slug = data.slug ? String(data.slug) : filename.replace(/\.mdx?$/, '')

  return {
    slug,
    title:         String(data.title       ?? ''),
    date:          String(data.date        ?? ''),
    updated:       data.updated ? String(data.updated) : undefined,
    excerpt:       String(data.excerpt     ?? ''),
    category:      data.category   as BlogCategory,
    readTime:      String(data.readTime    ?? '5 min read'),
    coverImage:    String(data.coverImage  ?? ''),
    featured:      Boolean(data.featured),
    // Default to published=true when the field is absent so existing posts
    // keep working. Only the explicit `published: false` hides a post.
    published:     data.published === undefined ? true : Boolean(data.published),
    autoGenerated: Boolean(data.autoGenerated),
    targetKeyword: data.targetKeyword ? String(data.targetKeyword) : undefined,
    content,
  }
}

export function getAllPosts(): BlogPost[] {
  if (!fs.existsSync(POSTS_DIR)) return []
  return fs
    .readdirSync(POSTS_DIR)
    .filter((f) => /\.mdx?$/.test(f))
    .map(readPostFile)
    .filter((p): p is BlogPost => p !== null)
    // Hide drafts (published: false) from the listing and static params.
    .filter((p) => p.published !== false)
    .sort((a, b) => (a.date < b.date ? 1 : -1))
}

export function getPostBySlug(slug: string): BlogPost | null {
  // Fast path: filename matches the slug.
  const direct = readPostFile(`${slug}.mdx`) ?? readPostFile(`${slug}.md`)
  if (direct && direct.slug === slug) return direct
  // Fallback: scan all posts and match by frontmatter slug.
  return getAllPosts().find((p) => p.slug === slug) ?? null
}

export function getRelatedPosts(current: BlogPost, limit = 2): BlogPost[] {
  return getAllPosts()
    .filter((p) => p.slug !== current.slug)
    .sort((a, b) => {
      const aMatch = a.category === current.category ? 1 : 0
      const bMatch = b.category === current.category ? 1 : 0
      if (aMatch !== bMatch) return bMatch - aMatch
      return a.date < b.date ? 1 : -1
    })
    .slice(0, limit)
}
