export const packages = [
  {
    id: 'bridal',
    name: 'Bridal',
    tagline: 'Ceremony, Reception, Nikkah, Walima, Baraat',
    price: '$600',
    priceValue: 600,
    priceNote: 'per person per event',
    highlight: true,
    includes: [
      'HD Waterproof Makeup',
      'Hairstyling',
      'Premium mink lashes',
      'Dupatta setting',
      'Jewelry setting',
      'Hair padding and pins',
      '30-min consultation call (3–4 weeks before)',
      'Touchup kit',
    ],
  },
  {
    id: 'pre-bridal',
    name: 'Pre-Bridal',
    tagline: 'Rokah, Jagoo, Engagement, Mehndi, Sangeet',
    price: '$450',
    priceValue: 450,
    priceNote: 'per person per event',
    highlight: false,
    includes: [
      'HD Waterproof Makeup',
      'Hairstyling',
      'Premium mink lashes',
      'Light dupatta setting (no head cover)',
      'Hair padding and pins',
    ],
  },
  {
    id: 'full-glam',
    name: 'Full Glam',
    tagline: 'eShoot, Baby Shower, Sister/Brother Weddings',
    price: '$350',
    priceValue: 350,
    priceNote: 'per person per event',
    highlight: false,
    includes: [
      'HD Waterproof Makeup',
      'Hairstyling',
      'Premium mink lashes',
      'Hair pins',
    ],
  },
  {
    id: 'party',
    name: 'Regular Party',
    tagline: 'Everyday events and celebrations',
    price: '$250',
    priceValue: 250,
    priceNote: 'per person per event',
    highlight: false,
    includes: [
      'Makeup (regular finish)',
      'Regular lashes',
      'Hair pins',
      'Simple hairdo, updos, curls, basic volume',
    ],
  },
] as const

export type Package = (typeof packages)[number]
